# Marketing Mix Model Configuration

# Target variable
target: Sales

# Channels for investment
channels:
  - name: TV_Spend
    bounds: [0, None]
    is_active : True
    decay:
      init : 0.5
      upper : 0.99
      lower : 0
    saturation_type : 'hill'
    k:
      init : 
      upper : 10
      lower : 0.001
    x0:
      init : 
      upper : 10
      lower : 0.001      
  - name: Radio_Spend
    bounds: [0.05, None]
    is_active : True
    decay:
      init : 0.5
      upper : 0.99
      lower : 0
    saturation_type : 'hill'
    k:
      init : 
      upper : 10
      lower : 0.001
    x0:
      init : 
      upper : 10
      lower : 0.001      
  - name: Digital_Spend
    bounds: [0, None]
    is_active : True
    decay:
      init : 0.5
      upper : 0.99
      lower : 0
    saturation_type : 'hill'
    k:
      init : 
      upper : 10
      lower : 0.001
    x0:
      init : 
      upper : 10
      lower : 0.001  
 
# Additional columns and their bounds
additional_columns:
  - name: Competitor_Spend
    bounds: [None, None]
    is_active : true
  - name: Promo_Pressure
    bounds: [0, None]
    is_active : True
  - name: COVID_Effect
    bounds: [100, 200]
    is_active : True
  - name: Sales_seasonal
    bounds: [0, None]
    is_active : True

# Baseline bounds
baseline:
  bounds: [0, None]
  is_active : True